#!/usr/bin/env python3
"""
build_signify_manifest.py -- Tier 5 SHA-256 + Ed25519 boot chain.

Walks a list of (initrd_name, host_path) pairs, computes the SHA-256 of
each host file, signs the resulting manifest with Ed25519, and writes
the binary manifest at the requested output path. The manifest is
consumed by `services/init/src/signify.rs::verify_manifest`.

The signing key is derived deterministically from a fixed seed so dev
builds are reproducible without key management. For production
deployments the seed should be replaced with a real keypair held
offline; the public key would still be committed for verification.

Format v2 (little-endian):

    magic       u32   = 0x53494732  ("SIG2")
    entry_count u32
    entries[count]:
        name_len  u16
        name      name_len bytes  (no NUL)
        digest    32 bytes        (raw SHA-256)
    pubkey      32 bytes          (raw Ed25519 public key)
    signature   64 bytes          (Ed25519 over bytes [0 .. pubkey_off))

The signature explicitly does NOT cover the pubkey or signature
themselves; the pubkey is included in the manifest only as a
self-describing aid. Init's verifier compares the embedded pubkey
against a const baked into the binary at compile time, rejecting any
attempt to swap the manifest+pubkey together.

Side effects:
  * `services/init/src/sigkey_generated.rs` is rewritten with the
    derived public key as a Rust const. init's signify module includes
    this file via `include!`.

Usage:
    python scripts/build_signify_manifest.py \
        --output target/sigmanifest \
        --pair name1=path1 name2=path2 ...
"""
import argparse
import hashlib
import os
import struct
import sys

from cryptography.hazmat.primitives.asymmetric.ed25519 import (
    Ed25519PrivateKey,
    Ed25519PublicKey,
)
from cryptography.hazmat.primitives import serialization

MAGIC_V2 = 0x53494732  # "SIG2"
SIGKEY_SEED_TEXT = b"sotOS-tier5-signify-dev-seed-v1"
GENERATED_RS = "services/init/src/sigkey_generated.rs"


def derive_keypair(seed_text: bytes) -> tuple[Ed25519PrivateKey, bytes]:
    """Deterministically derive an Ed25519 keypair from a fixed seed."""
    seed = hashlib.sha256(seed_text).digest()  # 32 bytes
    sk = Ed25519PrivateKey.from_private_bytes(seed)
    pk_bytes = sk.public_key().public_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PublicFormat.Raw,
    )
    return sk, pk_bytes


def write_pubkey_rs(path: str, pk_bytes: bytes) -> None:
    """Generate `sigkey_generated.rs` with the public key as a const."""
    assert len(pk_bytes) == 32
    bytes_lit = ", ".join(f"0x{b:02x}" for b in pk_bytes)
    content = (
        "// AUTO-GENERATED by scripts/build_signify_manifest.py\n"
        "// DO NOT EDIT BY HAND. Regenerate via `just sigmanifest`.\n"
        "//\n"
        "// Tier 5 boot chain: Ed25519 public key embedded into init.\n"
        "// signify::verify_manifest() rejects any manifest whose trailing\n"
        "// pubkey doesn't byte-match this constant.\n"
        "\n"
        f"pub const SIGKEY_PUB: [u8; 32] = [{bytes_lit}];\n"
    )
    os.makedirs(os.path.dirname(os.path.abspath(path)) or ".", exist_ok=True)
    # Only rewrite if changed (so init's incremental build doesn't churn).
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            if f.read() == content:
                return
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--output", required=True, help="Output manifest path")
    ap.add_argument(
        "--pair",
        action="append",
        default=[],
        help="initrd_name=host_path pair (repeatable)",
    )
    args = ap.parse_args()

    pairs = []
    for spec in args.pair:
        if "=" not in spec:
            print(f"bad --pair spec (need name=path): {spec}", file=sys.stderr)
            return 2
        name, path = spec.split("=", 1)
        pairs.append((name, path))

    sk, pk_bytes = derive_keypair(SIGKEY_SEED_TEXT)

    # Build the signed body (everything before pubkey + signature).
    body = bytearray()
    body += struct.pack("<II", MAGIC_V2, len(pairs))

    total_bytes = 0
    for name, path in pairs:
        try:
            with open(path, "rb") as f:
                data = f.read()
        except OSError as e:
            print(f"signify: {path}: {e}", file=sys.stderr)
            return 3
        digest = hashlib.sha256(data).digest()
        name_b = name.encode("utf-8")
        if len(name_b) > 0xFFFF:
            print(f"signify: name too long: {name}", file=sys.stderr)
            return 4
        body += struct.pack("<H", len(name_b))
        body += name_b
        body += digest
        total_bytes += len(data)

    signature = sk.sign(bytes(body))
    assert len(signature) == 64

    out = bytearray(body)
    out += pk_bytes
    out += signature

    os.makedirs(os.path.dirname(os.path.abspath(args.output)) or ".", exist_ok=True)
    with open(args.output, "wb") as f:
        f.write(out)

    write_pubkey_rs(GENERATED_RS, pk_bytes)

    print(
        f"signify: wrote {args.output} ({len(out)} bytes), "
        f"{len(pairs)} entries covering {total_bytes:,} bytes, "
        f"Ed25519 sig=64B, pubkey=32B",
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
