#!/usr/bin/env python3
"""
build_signify_manifest.py -- Tier 5 SHA-256 + Ed25519 boot chain.

Walks a list of (initrd_name, host_path) pairs, computes the SHA-256 of
each host file, signs the resulting manifest with Ed25519, and writes
the binary manifest at the requested output path. The manifest is
consumed by `services/init/src/signify.rs::verify_manifest`.

# Key sources (production vs dev)

The script picks the signing key in this order:

  1. **`SIGNIFY_KEY` env var** (production path) -- absolute path to a
     32-byte raw Ed25519 private key file held OUTSIDE the repo on a
     hardware token, encrypted volume, or build server secret store.
     Use `just signify-keygen PATH=<path>` to generate one.

  2. **`--key <path>` CLI flag** (same as #1, override).

  3. **Deterministic dev seed** (default) -- the keypair is derived
     from a fixed string via SHA-256. Reproducible across builds, but
     anyone with the source can forge a manifest. Marked clearly in
     the script's stdout so dev builds aren't confused with prod.

The pubkey embedded into init via `services/init/src/sigkey_generated.rs`
matches whichever key was used at build time. A mismatch between the
key used to sign and the pubkey baked into init causes
`signify: pubkey != embedded SIGKEY_PUB` at boot.

# Format v2 (little-endian)

    magic       u32   = 0x53494732  ("SIG2")
    entry_count u32
    entries[count]:
        name_len  u16
        name      name_len bytes  (no NUL)
        digest    32 bytes        (raw SHA-256)
    pubkey      32 bytes          (raw Ed25519 public key)
    signature   64 bytes          (Ed25519 over bytes [0 .. pubkey_off))

The signature explicitly does NOT cover the pubkey or signature
themselves; the pubkey is included in the manifest only as a
self-describing aid. Init's verifier compares the embedded pubkey
against a const baked into the binary at compile time, rejecting any
attempt to swap the manifest+pubkey together.

# Side effects

  * `services/init/src/sigkey_generated.rs` is rewritten with the
    derived/loaded public key as a Rust const. init's signify module
    includes this file via `include!`.

# Usage

    python scripts/build_signify_manifest.py \
        --output target/sigmanifest \
        --pair name1=path1 name2=path2 ...

    SIGNIFY_KEY=/secrets/sotbsd-signify.key \
        python scripts/build_signify_manifest.py ...
"""
import argparse
import hashlib
import os
import struct
import sys

from cryptography.hazmat.primitives.asymmetric.ed25519 import (
    Ed25519PrivateKey,
    Ed25519PublicKey,
)
from cryptography.hazmat.primitives import serialization

MAGIC_V2 = 0x53494732  # "SIG2"
SIGKEY_SEED_TEXT = b"sotOS-tier5-signify-dev-seed-v1"
GENERATED_RS = "services/init/src/sigkey_generated.rs"


def derive_keypair(seed_text: bytes) -> tuple[Ed25519PrivateKey, bytes]:
    """Deterministically derive an Ed25519 keypair from a fixed seed."""
    seed = hashlib.sha256(seed_text).digest()  # 32 bytes
    sk = Ed25519PrivateKey.from_private_bytes(seed)
    pk_bytes = sk.public_key().public_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PublicFormat.Raw,
    )
    return sk, pk_bytes


def load_keypair_from_file(path: str) -> tuple[Ed25519PrivateKey, bytes]:
    """Load a 32-byte raw Ed25519 private key from a file held offline."""
    with open(path, "rb") as f:
        priv = f.read()
    if len(priv) != 32:
        raise ValueError(
            f"signify: key file {path} must be exactly 32 bytes (got {len(priv)})"
        )
    sk = Ed25519PrivateKey.from_private_bytes(priv)
    pk_bytes = sk.public_key().public_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PublicFormat.Raw,
    )
    return sk, pk_bytes


def select_keypair(cli_key: str | None) -> tuple[Ed25519PrivateKey, bytes, str]:
    """Pick the signing key per the precedence rules. Returns
    `(sk, pk_bytes, source_label)` for diagnostic logging."""
    env_key = os.environ.get("SIGNIFY_KEY")
    if cli_key:
        sk, pk = load_keypair_from_file(cli_key)
        return sk, pk, f"file ({cli_key})"
    if env_key:
        sk, pk = load_keypair_from_file(env_key)
        return sk, pk, f"env SIGNIFY_KEY ({env_key})"
    sk, pk = derive_keypair(SIGKEY_SEED_TEXT)
    return sk, pk, "DEV SEED (insecure -- do not use in production)"


def write_pubkey_rs(path: str, pk_bytes: bytes) -> None:
    """Generate `sigkey_generated.rs` with the public key as a const."""
    assert len(pk_bytes) == 32
    bytes_lit = ", ".join(f"0x{b:02x}" for b in pk_bytes)
    content = (
        "// AUTO-GENERATED by scripts/build_signify_manifest.py\n"
        "// DO NOT EDIT BY HAND. Regenerate via `just sigmanifest`.\n"
        "//\n"
        "// Tier 5 boot chain: Ed25519 public key embedded into init.\n"
        "// signify::verify_manifest() rejects any manifest whose trailing\n"
        "// pubkey doesn't byte-match this constant.\n"
        "\n"
        f"pub const SIGKEY_PUB: [u8; 32] = [{bytes_lit}];\n"
    )
    os.makedirs(os.path.dirname(os.path.abspath(path)) or ".", exist_ok=True)
    # Only rewrite if changed (so init's incremental build doesn't churn).
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            if f.read() == content:
                return
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--output", required=True, help="Output manifest path")
    ap.add_argument(
        "--pair",
        action="append",
        default=[],
        help="initrd_name=host_path pair (repeatable)",
    )
    ap.add_argument(
        "--key",
        default=None,
        help="Path to a 32-byte raw Ed25519 private key (production). "
             "Overrides SIGNIFY_KEY env var.",
    )
    args = ap.parse_args()

    pairs = []
    for spec in args.pair:
        if "=" not in spec:
            print(f"bad --pair spec (need name=path): {spec}", file=sys.stderr)
            return 2
        name, path = spec.split("=", 1)
        pairs.append((name, path))

    try:
        sk, pk_bytes, key_source = select_keypair(args.key)
    except (OSError, ValueError) as e:
        print(f"signify: {e}", file=sys.stderr)
        return 5
    print(f"signify: signing with key from {key_source}")

    # Build the signed body (everything before pubkey + signature).
    body = bytearray()
    body += struct.pack("<II", MAGIC_V2, len(pairs))

    total_bytes = 0
    for name, path in pairs:
        try:
            with open(path, "rb") as f:
                data = f.read()
        except OSError as e:
            print(f"signify: {path}: {e}", file=sys.stderr)
            return 3
        digest = hashlib.sha256(data).digest()
        name_b = name.encode("utf-8")
        if len(name_b) > 0xFFFF:
            print(f"signify: name too long: {name}", file=sys.stderr)
            return 4
        body += struct.pack("<H", len(name_b))
        body += name_b
        body += digest
        total_bytes += len(data)

    signature = sk.sign(bytes(body))
    assert len(signature) == 64

    out = bytearray(body)
    out += pk_bytes
    out += signature

    os.makedirs(os.path.dirname(os.path.abspath(args.output)) or ".", exist_ok=True)
    with open(args.output, "wb") as f:
        f.write(out)

    write_pubkey_rs(GENERATED_RS, pk_bytes)

    print(
        f"signify: wrote {args.output} ({len(out)} bytes), "
        f"{len(pairs)} entries covering {total_bytes:,} bytes, "
        f"Ed25519 sig=64B, pubkey=32B",
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
