//! Structured documentation table for every LUCAS shell built-in.
//!
//! Kept in a dedicated module so the data block stays out of rendering logic.
//! Entries are `&'static` only — no heap, no runtime allocation.

use crate::help::{Category, CommandDoc};

/// Master registry. Order within a category controls list order.
pub const ALL_DOCS: &[CommandDoc] = &[
    // ----------------------------------------------------------------- File
    CommandDoc {
        name: "ls",
        category: Category::File,
        usage: "ls [path]",
        summary: "List directory contents.",
        examples: &["ls", "ls /bin"],
    },
    CommandDoc {
        name: "cat",
        category: Category::File,
        usage: "cat <file>",
        summary: "Print file contents to stdout.",
        examples: &["cat /etc/os-release", "cat notes.txt"],
    },
    CommandDoc {
        name: "write",
        category: Category::File,
        usage: "write <file> <text>",
        summary: "Write literal text into a file (overwrites).",
        examples: &["write hello.txt \"hi there\""],
    },
    CommandDoc {
        name: "rm",
        category: Category::File,
        usage: "rm <file>",
        summary: "Remove a regular file.",
        examples: &["rm stale.log"],
    },
    CommandDoc {
        name: "stat",
        category: Category::File,
        usage: "stat [path]",
        summary: "Show file metadata (size, mode, owner).",
        examples: &["stat /bin/ls", "stat ."],
    },
    CommandDoc {
        name: "hexdump",
        category: Category::File,
        usage: "hexdump <file>",
        summary: "Dump file contents as hex + ASCII.",
        examples: &["hexdump /bin/busybox"],
    },
    CommandDoc {
        name: "mkdir",
        category: Category::File,
        usage: "mkdir <dir>",
        summary: "Create a new directory.",
        examples: &["mkdir /tmp/work"],
    },
    CommandDoc {
        name: "rmdir",
        category: Category::File,
        usage: "rmdir <dir>",
        summary: "Remove an empty directory.",
        examples: &["rmdir /tmp/work"],
    },
    CommandDoc {
        name: "cd",
        category: Category::File,
        usage: "cd [dir]",
        summary: "Change current working directory. No arg = /.",
        examples: &["cd /tmp", "cd"],
    },
    CommandDoc {
        name: "pwd",
        category: Category::File,
        usage: "pwd",
        summary: "Print current working directory.",
        examples: &["pwd"],
    },
    CommandDoc {
        name: "snap",
        category: Category::File,
        usage: "snap <list|take|restore> [name]",
        summary: "Manage object-store copy-on-write snapshots.",
        examples: &["snap list", "snap take daily"],
    },

    // ----------------------------------------------------------------- Text
    CommandDoc {
        name: "echo",
        category: Category::Text,
        usage: "echo [text...]",
        summary: "Print arguments followed by a newline.",
        examples: &["echo hello", "echo \"$PATH\""],
    },
    CommandDoc {
        name: "head",
        category: Category::Text,
        usage: "head [-n N] <file>",
        summary: "Print the first N (default 10) lines of a file.",
        examples: &["head /etc/hosts", "head -n 3 log.txt"],
    },
    CommandDoc {
        name: "tail",
        category: Category::Text,
        usage: "tail [-n N] <file>",
        summary: "Print the last N (default 10) lines of a file.",
        examples: &["tail log.txt", "tail -n 20 log.txt"],
    },
    CommandDoc {
        name: "grep",
        category: Category::Text,
        usage: "grep <pattern> <file>",
        summary: "Print lines matching a substring pattern.",
        examples: &["grep error log.txt", "grep root /etc/passwd"],
    },
    CommandDoc {
        name: "wc",
        category: Category::Text,
        usage: "wc <file>",
        summary: "Count lines, words, and bytes in a file.",
        examples: &["wc /etc/hosts"],
    },
    CommandDoc {
        name: "sort",
        category: Category::Text,
        usage: "sort <file>",
        summary: "Sort the lines of a file ascending.",
        examples: &["sort names.txt"],
    },
    CommandDoc {
        name: "uniq",
        category: Category::Text,
        usage: "uniq <file>",
        summary: "Filter adjacent duplicate lines.",
        examples: &["sort names.txt | uniq"],
    },
    CommandDoc {
        name: "diff",
        category: Category::Text,
        usage: "diff <a> <b>",
        summary: "Show a simple line-by-line difference between two files.",
        examples: &["diff a.txt b.txt"],
    },
    CommandDoc {
        name: "read",
        category: Category::Text,
        usage: "read VAR",
        summary: "Read a line from stdin into a shell variable.",
        examples: &["read name"],
    },

    // --------------------------------------------------------------- System
    CommandDoc {
        name: "uname",
        category: Category::System,
        usage: "uname",
        summary: "Print system name, version and architecture.",
        examples: &["uname"],
    },
    CommandDoc {
        name: "uptime",
        category: Category::System,
        usage: "uptime",
        summary: "Show how long the kernel has been running.",
        examples: &["uptime"],
    },
    CommandDoc {
        name: "caps",
        category: Category::System,
        usage: "caps",
        summary: "Dump the current process capability table.",
        examples: &["caps"],
    },
    CommandDoc {
        name: "ps",
        category: Category::System,
        usage: "ps",
        summary: "List processes currently running in sotX.",
        examples: &["ps"],
    },
    CommandDoc {
        name: "top",
        category: Category::System,
        usage: "top",
        summary: "Show thread-level CPU/memory usage snapshot.",
        examples: &["top"],
    },
    CommandDoc {
        name: "kill",
        category: Category::System,
        usage: "kill <pid> [signal]",
        summary: "Send a signal (default TERM) to a process.",
        examples: &["kill 42", "kill 42 KILL"],
    },
    CommandDoc {
        name: "getpid",
        category: Category::System,
        usage: "getpid",
        summary: "Print the shell's own process id.",
        examples: &["getpid"],
    },
    CommandDoc {
        name: "fork",
        category: Category::System,
        usage: "fork",
        summary: "Fork the shell into a child process (debug helper).",
        examples: &["fork"],
    },
    CommandDoc {
        name: "exec",
        category: Category::System,
        usage: "exec <program>",
        summary: "Replace the shell image with a program from initrd/VFS.",
        examples: &["exec hello-linux"],
    },
    CommandDoc {
        name: "services",
        category: Category::System,
        usage: "services",
        summary: "List services registered with the kernel registry.",
        examples: &["services"],
    },
    CommandDoc {
        name: "threads",
        category: Category::System,
        usage: "threads",
        summary: "Print total number of kernel threads.",
        examples: &["threads"],
    },
    CommandDoc {
        name: "meminfo",
        category: Category::System,
        usage: "meminfo",
        summary: "Show free / total physical frame counts.",
        examples: &["meminfo"],
    },
    CommandDoc {
        name: "bench",
        category: Category::System,
        usage: "bench",
        summary: "Run a tiny micro-benchmark of syscalls and IPC.",
        examples: &["bench"],
    },
    CommandDoc {
        name: "jobs",
        category: Category::System,
        usage: "jobs",
        summary: "List background jobs started with `cmd &`.",
        examples: &["jobs"],
    },
    CommandDoc {
        name: "fg",
        category: Category::System,
        usage: "fg [n]",
        summary: "Bring background job n to the foreground.",
        examples: &["fg", "fg 2"],
    },
    CommandDoc {
        name: "bg",
        category: Category::System,
        usage: "bg [n]",
        summary: "Resume job n in the background.",
        examples: &["bg 1"],
    },

    // ------------------------------------------------------------------- Net
    CommandDoc {
        name: "resolve",
        category: Category::Net,
        usage: "resolve <host>",
        summary: "Resolve a DNS name to an IPv4 address.",
        examples: &["resolve example.com"],
    },
    CommandDoc {
        name: "ping",
        category: Category::Net,
        usage: "ping <host|ip>",
        summary: "Send ICMP echo requests to a host.",
        examples: &["ping 10.0.2.2", "ping example.com"],
    },
    CommandDoc {
        name: "traceroute",
        category: Category::Net,
        usage: "traceroute <host|ip>",
        summary: "Trace the routers between here and a host.",
        examples: &["traceroute example.com"],
    },
    CommandDoc {
        name: "wget",
        category: Category::Net,
        usage: "wget [-O file] [-q] <url>",
        summary: "Fetch a URL over HTTP and write to stdout or a file.",
        examples: &["wget http://example.com", "wget -O /tmp/x.html http://example.com"],
    },

    // --------------------------------------------------------------- Script
    CommandDoc {
        name: "export",
        category: Category::Script,
        usage: "export KEY=VALUE",
        summary: "Set a shell environment variable.",
        examples: &["export PATH=/bin:/usr/bin"],
    },
    CommandDoc {
        name: "env",
        category: Category::Script,
        usage: "env",
        summary: "Print all exported environment variables.",
        examples: &["env"],
    },
    CommandDoc {
        name: "unset",
        category: Category::Script,
        usage: "unset KEY",
        summary: "Remove an environment variable.",
        examples: &["unset TMPVAR"],
    },
    CommandDoc {
        name: "history",
        category: Category::Script,
        usage: "history",
        summary: "Show recently executed command lines.",
        examples: &["history"],
    },
    CommandDoc {
        name: "source",
        category: Category::Script,
        usage: "source <file>",
        summary: "Execute a script file in the current shell.",
        examples: &["source /etc/profile", ". ./vars.sh"],
    },
    CommandDoc {
        name: "true",
        category: Category::Script,
        usage: "true",
        summary: "Do nothing and return success (exit 0).",
        examples: &["true && echo ok"],
    },
    CommandDoc {
        name: "false",
        category: Category::Script,
        usage: "false",
        summary: "Do nothing and return failure (exit 1).",
        examples: &["false || echo fallback"],
    },
    CommandDoc {
        name: "sleep",
        category: Category::Script,
        usage: "sleep <seconds>",
        summary: "Pause execution for the given whole seconds.",
        examples: &["sleep 2"],
    },

    // ----------------------------------------------------------------- Util
    CommandDoc {
        name: "help",
        category: Category::Util,
        usage: "help [command]",
        summary: "Show this list, or detailed docs for one command.",
        examples: &["help", "help ls"],
    },
    CommandDoc {
        name: "man",
        category: Category::Util,
        usage: "man <command>",
        summary: "Show detailed documentation (alias of `help <cmd>`).",
        examples: &["man ls", "man grep"],
    },
    CommandDoc {
        name: "type",
        category: Category::Util,
        usage: "type <name>",
        summary: "Report whether a name is builtin, function, or on disk.",
        examples: &["type ls", "type myFunc"],
    },
    CommandDoc {
        name: "exit",
        category: Category::Util,
        usage: "exit",
        summary: "Leave the LUCAS shell.",
        examples: &["exit"],
    },
];
