//! Fuzz target: `sotos_common::Syscall::try_from_u64`.
//!
//! The kernel's syscall dispatcher receives an arbitrary `u64` from
//! userspace in `rax`. Every value must either decode into a valid
//! variant or be cleanly rejected -- no panic, no UB. This harness
//! drives the pure decoder with libFuzzer-generated bytes.
//!
//! Coverage invariants checked on every input:
//!
//! 1. `try_from_u64(n)` never panics.
//! 2. If it returns `Some(v)`, then `v as u64 == n` (round-trip).
//! 3. `TryFrom<u64>` agrees with `try_from_u64` for the same input.

#![no_main]

use libfuzzer_sys::fuzz_target;
use sotos_common::Syscall;

fuzz_target!(|data: &[u8]| {
    if data.len() < 8 {
        return;
    }
    let n = u64::from_le_bytes(data[..8].try_into().unwrap());

    // 1. Primary API -- must never panic on any u64.
    let decoded = Syscall::try_from_u64(n);

    // 2. Round-trip: if decode succeeds, the discriminant must match.
    if let Some(sc) = decoded {
        assert_eq!(sc as u64, n, "decoded variant must equal input discriminant");
    }

    // 3. TryFrom impl must agree with the inherent method.
    let via_trait: Result<Syscall, _> = core::convert::TryFrom::try_from(n);
    match (decoded, via_trait) {
        (Some(a), Ok(b)) => assert_eq!(a as u64, b as u64),
        (None, Err(_)) => {}
        _ => panic!("try_from_u64 and TryFrom impl disagree on {n:#x}"),
    }
});
